export const INIT_GET_PROJECTS = 'INIT_GET_PROJECTS';
export const SUCCESS_GET_PROJECTS = 'SUCCESS_GET_PROJECTS';
export const SET_PROJECTS = 'SET_PROJECTS';

export const INIT_GET_PROJECT = 'INIT_GET_PROJECT';
export const SUCCESS_GET_PROJECT = 'SUCCESS_GET_PROJECT';
export const SET_PROJECT = 'SET_PROJECT';
